### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by LibreBai** [Spriteware/lt-codes-python#1]
For the decoding of some files, even if enough packets are collected, the decoding cannot be successful. How can I solve this problem?

**Comment by Spriteware** [comment]
Hi,

Can you describe a bit more your problem? What's happening, what do you want to transfer?

LT Codes is a probabilistic system, it means that you are never 100% sure to have the decoding successful, however you can tune the parameters to get it work 99.99% of the time.
You can change the probabilistic distribution of the number of blocks required to create a Symbol, you can also split the file if it is too large (you have a better chance to successfully small files), etc....

**Comment by LibreBai** [comment]
Thanks,
I use lt_codes.py to test the file. For some files, there is a high probability of recovery failure. But for some small files, there will never be a decoding failure.
The file size is 1148889 bytes. A total of 36 blocks.Probably a 50% probability of recovery failure.Is this a normal phenomenon?

**Comment by Spriteware** [comment]
For a size like this, the algorithm should work very easily.

Do you use the --systematic option? What is the redundancy of your encoding? I used 1.5 in a lot of my tests.
Do you mind sharing the file that doesn't work or an equivalent?

**Comment by LibreBai** [comment]
The file I placed under this URL https://github.com/yaodongb/PythonLearning/blob/master/abc.  https://github.com/yaodongb/PythonLearning/blob/master/WIN7Activation.exe.
I did not add other parameters.
`python3 lt_codes.py abc` .This is my execution order.
The result is similar to this “----- Solved Blocks  2/18 -- All blocks are not recovered, we cannot proceed the file writing”.
I have found several files that are like this. But some files never show errors.

**Comment by Spriteware** [comment]
This is absolutely how the program should work. As I told you : 
>LT Codes is a probabilistic system, it means that you are never 100% sure to have the decoding successful, however **you can tune the parameters to get it work 99.99% of the time.**

The default redundancy is 2.0, which is still not enough if you don't use the systematic encoding (not enabled by default, you can enable it with `--systematic`).   
Your file is spitted in 18 blocks but with the default parameters you will only create 36 drops: according to the distribution used in the encoding, the probability that one block is not sent within a drop is still high, that gives you the following result:
```
$ ./lt_codes.py abc
Redundancy: 2.0
Systematic: False
Filesize: 1148889 bytes
Blocks: 18
Drops: 36

Generating graph...
Ready for encoding.
-- Encoding: 36/36 - 100.00% symbols at 318.31 MB/s       ~0.01s
----- Correctly dropped 36 symbols (packet size=65536)
Graph built back. Ready for decoding.

----- Solved Blocks  9/18 --
All blocks are not recovered, we cannot proceed the file writing
```

If you add more drops by increasing the redundancy, you get a higher probability of a successful encoding/decoding:
```
$ ./lt_codes.py abc -r 6
Redundancy: 6.0
Systematic: False
Filesize: 1148889 bytes
Blocks: 18
Drops: 108

Generating graph...
Ready for encoding.
-- Encoding: 108/108 - 100.00% symbols at 557.91 MB/s       ~0.01s
----- Correctly dropped 108 symbols (packet size=65536)
Graph built back. Ready for decoding.
-- Decoding: 18/18 - 100.00% symbols at 185.72 MB/s       ~0.01s
----- Solved Blocks 18/18 --
Wrote 1148889 bytes in abc-copy
```

Or you can chose to **send at least once each block: the is the systematic encoding** that you enable with `--systematic`:
```
$ ./lt_codes.py abc --systematic
Redundancy: 2.0
Systematic: True
Filesize: 1148889 bytes
Blocks: 18
Drops: 36

Generating graph...
Ready for encoding.
-- Encoding: 36/36 - 100.00% symbols at 729.34 MB/s       ~0.00s
----- Correctly dropped 36 symbols (packet size=65536)
Graph built back. Ready for decoding.
-- Decoding: 18/18 - 100.00% symbols at 1022.13 MB/s       ~0.00s
----- Solved Blocks 18/18 --
Wrote 1148889 bytes in abc-copy
```

**Comment by LibreBai** [comment]
These methods can be solved, thanks
