### ISSUE TITLE
https://franpapers.com/en/algorithmic/2018-introduction-to-fountain-codes-lt-codes-with-python/

### ISSUE THREAD

**Issue by Praskand** [Spriteware/lt-codes-python#5]
https://franpapers.com/en/algorithmic/2018-introduction-to-fountain-codes-lt-codes-with-python/ no longer works

**Comment by ashleylamont** [comment]
https://web.archive.org/web/20181110184516/https://franpapers.com/en/algorithmic/2018-introduction-to-fountain-codes-lt-codes-with-python/

**Comment by Praskand** [comment]
thanks ashleylamont!
